export interface ProductionParams {
  /** Finished units per calendar year (required for throughput math). */
  unitsPerYear: number
  workingDaysPerYear?: number
  shiftsPerDay?: number
  hoursPerShift?: number
  /** Overall equipment effectiveness 0–1, default 0.85 on server. */
  oee?: number
}

export interface ThroughputAnalysis {
  unitsPerYear: number
  workingDaysPerYear: number
  shiftsPerDay: number
  hoursPerShift: number
  oee: number
  taktSec: number
  workedSecondsPerYear: number
  effectiveSecondsPerYear: number
  bottleneckNodeId: string | null
  bottleneckLabel: string
  bottleneckCycleSec: number
  lineTheoreticalUnitsPerYear: number
  meetsTakt: boolean
  parallelStationsSuggested: number
  warnings: string[]
}

export interface FactoryNode {
  id: string
  machineType: string
  label: string
  x: number
  y: number
  width: number
  height: number
  notes?: string
  cycleTimeSec?: number
  isBottleneck?: boolean
}

export interface FactoryEdge {
  id: string
  source: string
  target: string
  label?: string
}

export interface FactoryLayout {
  title: string
  nodes: FactoryNode[]
  edges: FactoryEdge[]
  /** True when layout was generated by built-in demo (no LLM). */
  demo?: boolean
  demoHint?: string
  /** Present when annual volume was provided at generation time. */
  throughput?: ThroughputAnalysis
}

/** Empty canvas for “start from scratch” — add machines from the palette. */
export function createEmptyFactoryLayout(): FactoryLayout {
  return {
    title: 'New line plan',
    nodes: [],
    edges: [],
  }
}

export interface HealthStatus {
  status?: string
  llmReady?: boolean
  demoMode?: boolean
  provider?: string
  model?: string | null
  /** Legacy fields (Ollama) */
  ollamaRunning: boolean
  modelReady: boolean
  models: string[]
}

/** Parse API error body whether it is JSON or plain text / HTML */
async function parseErrorBody(res: Response): Promise<string> {
  const text = await res.text()
  const trimmed = text.trim().slice(0, 500)
  if (res.status === 405) {
    return (
      'Method not allowed (405). Usually the hosting sent your API request to the static page instead of `/api/*`. ' +
      'If you use Vercel, redeploy with the latest `vercel.json` (SPA fallback must not catch `/api/`). ' +
      'Locally, run `npm run dev` so the API on port 3001 is up.'
    )
  }
  if (!trimmed) {
    return `Request failed (${res.status} ${res.statusText}). Locally: run \`npm run dev\` (API on port 3001). On Vercel, check deployment logs.`
  }
  try {
    const json = JSON.parse(trimmed) as { error?: string; message?: string; fix?: string }
    const parts = [json.error, json.message, json.fix].filter(Boolean)
    if (parts.length) return parts.join(' — ')
  } catch {
    /* not JSON */
  }
  if (trimmed.startsWith('<')) {
    return `Server returned HTML (${res.status}) instead of JSON — often a rewrite or wrong URL. Locally run \`npm run dev\`; on Vercel check \`/api/generate\` routing.`
  }
  return trimmed || `Request failed (${res.status})`
}

export async function generateLayout(
  prompt: string,
  production?: ProductionParams | null,
): Promise<FactoryLayout> {
  let res: Response
  try {
    res = await fetch('/api/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt,
        ...(production && production.unitsPerYear > 0 ? { production } : {}),
      }),
    })
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    throw new Error(
      `Cannot reach API: ${msg}. Run both servers: npm run dev (starts API on :3001 and Vite on :5173).`,
    )
  }

  if (!res.ok) {
    const message = await parseErrorBody(res)
    throw new Error(message)
  }

  const text = await res.text()
  try {
    return JSON.parse(text) as FactoryLayout
  } catch {
    throw new Error('Invalid JSON from server. Check that node server.js is the latest version.')
  }
}

export async function checkHealth(): Promise<HealthStatus> {
  try {
    const res = await fetch('/api/health')
    const data = (await res.json()) as Partial<HealthStatus> & Record<string, unknown>
    const llmReady = Boolean(data.llmReady)
    const demoMode = Boolean(data.demoMode)
    return {
      ...data,
      status: typeof data.status === 'string' ? data.status : 'ok',
      llmReady,
      demoMode,
      provider: typeof data.provider === 'string' ? data.provider : undefined,
      model: data.model != null ? String(data.model) : null,
      ollamaRunning: Boolean(data.ollamaRunning),
      modelReady: Boolean(data.modelReady ?? llmReady),
      models: Array.isArray(data.models) ? (data.models as string[]) : [],
    }
  } catch {
    return {
      ollamaRunning: false,
      modelReady: false,
      demoMode: true,
      llmReady: false,
      models: [],
    }
  }
}
